### ISSUE TITLE
Add Animation

### ISSUE THREAD

**Issue by gshraddha17** [KalashJain591/Web-Development-Snippets#2]
I want to add an animation wherein the shapes and colour will change after a few seconds and the shapes will keep on moving on the screen.
Please assign me this issue.
https://user-images.githubusercontent.com/94107629/196474728-80c4b535-05d5-42c8-9e6b-d550d763e5a3.mp4

**Comment by KalashJain591** [comment]
@gshraddha17 the issue has been assigned  to you.
