### ISSUE TITLE
In backend snippets , add code  to find  factorial and power of a given number in javascript 

### ISSUE THREAD

**Issue by KalashJain591** [KalashJain591/Web-Development-Snippets#8]

**Comment by Nikita0509** [comment]
can u assign this issue to me under hacktoberfest fest

**Comment by ghost** [comment]
Hi 
Can you please assign this Issue to me under Hacktoberfest?

**Comment by KalashJain591** [comment]
The issue has been assingned to 2 peoples . Do complete as early as possible to get hactoberfest accepted tag
@tarunmishra071 
@Nikita0509

**Comment by Nikita0509** [comment]
Please check the PR #12
